
#define GRASS_TILE_DIMENSION  15
#define TERRAIN_WIDTH 2480
#define TERRAIN_HEIGHT 2480
#define GRASS_TILE_COUNT_X (TERRAIN_WIDTH/GRASS_TILE_DIMENSION)
#define GRASS_TILE_COUNT_Y (TERRAIN_HEIGHT/GRASS_TILE_DIMENSION)
#define GRASS_TILE_COUNT (GRASS_TILE_COUNT_X*GRASS_TILE_COUNT_Y)

#define NUMBER_OF_GRASS_LOD 4

#define MAX_GRASS_CAP  100000000